#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

# rotate() {
# 	degree="$1"
# 	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
# 		case "$(file -b -i "$file")" in

#     # image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
# 		# *)           mogrify  -rotate "$degree" "$file" ;;

#     *)
#       convert \"${file}\" -rotate "${degree}"
#       ;;

# 		esac
# 	done
# }

view() {
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in

    *)
      sxiv -ps f "${file}" &
      ;;

		esac
	done
}

HELP_TXT="
Extra key bindings
-------------------
C-x C-h: help
C-x C-x: copy (one line)
C-x C-c: copy (multiline)
C-x C-g: gimp
C-x C-b: brave
C-x C-i: sxiv
"

case "$1" in

  # ------ Help
  "C-h")
    notify-send "sxiv" "${HELP_TXT}"
    ;;


  # ------ Copy filenames (one line)
  "C-x")
    xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard
    notify-send "sxiv" "Filenames copied to clipboard (one line)"
    ;;

  # ------ Copy filenames (multiline)
  "C-c")
    xclip -in -filter | xclip -in -selection clipboard
    notify-send "sxiv" "Filenames copied to clipboard (multiline)"
    ;;

  # ------ gimp
  "C-g")
    tr '\n' '\0' | xargs -0 gimp
    ;;

  # ------ brave-brower
  "C-b")
    tr '\n' '\0' | xargs -0 brave-browser
    ;;

  # ------ sxiv
  "C-i")
    view
    ;;

  # ------ rotate 270
  # "C-l")
  #   rotate 270
  #   ;;

  # ------ rotate  90
  # "C-r")
  #   rotate  90
  #   ;;

  # ------ rotate 180
  # "C-u")
  #   rotate 180
  #   ;;

esac
